---
spring:
  config:
    activate:
      on-profile: test
  application:
    name: pankcakejob
  freemarker:
    template-loader-path: classpath:/web/app/
    suffix: .ftl
    charset: utf-8
    cache: false
    expose-request-attributes: true
    expose-session-attributes: true
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://gz-cynosdbmysql-grp-17pikoep.sql.tencentcdb.com:22639/pancake_job?serverTimezone=UTC
    username: HELLO
    password: JBGZ
server:
  port: 5000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  # ????mybatis?xml?????plus
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #?plus??
---
spring:
  profiles:
    active: test